### ISSUE TITLE
Infinite loop in Modul ProDrafts when saving a page (in combination with Page Reference)

### ISSUE THREAD

**Issue by Radon8472** [processwire/processwire-issues#1272]
### Short description of the issue

When A page contains `Page Refference` fields, the ProDarfts moduls runs into infinite loops while `ProDrafts::getPageDifferences`.

### Expected behavior

The page should be saved.

### Actual behavior

When you save a page or accept a Draft the page loads very long and is not correctly saved.
I did a deeper look into the modul to find the reason for this error and found out:

- The function `ProcessWire\ProDrafts::getPageDifferences()` runs in a endles loop until `max_execution_time` is reached
  - That happens because:
    - the function checks each field in the page for possible differences.
    - For fields of type `Page` and `PageArray` the function calls itself recursively to check all differences in the Page-/PageArray
      - When the field created with PageReference the Function checks the whole linked page for differences too
      - When this linked page contains other PageReference field, it follows them and does the next recursiv call

- The big problem comes when the linked pages have direct or indirect backlinks to one of the pages that contain the link to them. in that case the modul runs in an endles deep resursion.
e.g. the simple case is (Each page has a link to the other, so the modul)
```
PageA -> PageB -> PageA
```
Or more complex case:
```
PageA -> PageB -> PageC ...... PageZ -> PageA
```

### Optional: Screenshots/Links that demonstrate the issue

Your screenshots/links go here.

### Optional: Suggestion for a possible fix

A small change `ProDrafts.modul`:
  BEFORE the Recursiv calls in `getPageDifferences line 1026` and `getPageDifferences line 1037 you should check if the field is a `PageReference` 
  - if YES dont do a recursive call, Yust compare if the IDs of the Target-Page are changed
  - if NO continue with Recursive calls

### Steps to reproduce the issue

1. Install and setup `ProDrafts` Modul 
2. Create 2 Pages containg a `PageReference` - Field (Or any other field that contains a `PageReference` field)
3. Choose a Refference to the First Page (PageA) in the Reference Field of the First page
4. Suggest a Draft for PageB and set a link to PageA
5. Try to save this page and/or accept the Draft

### Setup/Environment
* ProcessWire version: 3.0.164
* Modul `ProDrafts v 0.0.8`  
- Modul `Page Reference  v 1.0.5`

### Stacktrace (when I trigger an Exception at the 100th recursion)
```
DEBUG MODUS ABLAUFVERFOLGUNG ($config->debug == true):
#0 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\Page), Object(ProcessWire\Page), true)
#1 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\FieldsetPage), Object(ProcessWire\FieldsetPage), true)
#2 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterPage), Object(ProcessWire\RepeaterPage), true)
#3 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterMatrixPage), Object(ProcessWire\RepeaterMatrixPage), true)
#4 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\Page), Object(ProcessWire\Page), true)
#5 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\FieldsetPage), Object(ProcessWire\FieldsetPage), true)
#6 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterPage), Object(ProcessWire\RepeaterPage), true)
#7 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterPage), Object(ProcessWire\RepeaterPage), true)
#8 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\FieldsetPage), Object(ProcessWire\FieldsetPage), true)
#9 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\Page), Object(ProcessWire\Page), true)
#10 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterMatrixPage), Object(ProcessWire\RepeaterMatrixPage), true)
#11 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\Page), Object(ProcessWire\Page), true)
#12 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\FieldsetPage), Object(ProcessWire\FieldsetPage), true)
#13 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterPage), Object(ProcessWire\RepeaterPage), true)
#14 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterPage), Object(ProcessWire\RepeaterPage), true)
#15 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\FieldsetPage), Object(ProcessWire\FieldsetPage), true)
#16 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\Page), Object(ProcessWire\Page), true)
#17 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterMatrixPage), Object(ProcessWire\RepeaterMatrixPage), true)
#18 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\Page), Object(ProcessWire\Page), true)
#19 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\FieldsetPage), Object(ProcessWire\FieldsetPage), true)
#20 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterPage), Object(ProcessWire\RepeaterPage), true)
#21 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterPage), Object(ProcessWire\RepeaterPage), true)
#22 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\FieldsetPage), Object(ProcessWire\FieldsetPage), true)
#23 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\Page), Object(ProcessWire\Page), true)
#24 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterMatrixPage), Object(ProcessWire\RepeaterMatrixPage), true)
#25 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\Page), Object(ProcessWire\Page), true)
#26 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\FieldsetPage), Object(ProcessWire\FieldsetPage), true)
#27 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterPage), Object(ProcessWire\RepeaterPage), true)
#28 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterPage), Object(ProcessWire\RepeaterPage), true)
#29 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\FieldsetPage), Object(ProcessWire\FieldsetPage), true)
#30 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\Page), Object(ProcessWire\Page), true)
#31 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterMatrixPage), Object(ProcessWire\RepeaterMatrixPage), true)
#32 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\Page), Object(ProcessWire\Page), true)
#33 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\FieldsetPage), Object(ProcessWire\FieldsetPage), true)
#34 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterPage), Object(ProcessWire\RepeaterPage), true)
#35 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterPage), Object(ProcessWire\RepeaterPage), true)
#36 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\FieldsetPage), Object(ProcessWire\FieldsetPage), true)
#37 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\Page), Object(ProcessWire\Page), true)
#38 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterMatrixPage), Object(ProcessWire\RepeaterMatrixPage), true)
#39 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\Page), Object(ProcessWire\Page), true)
#40 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\FieldsetPage), Object(ProcessWire\FieldsetPage), true)
#41 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterPage), Object(ProcessWire\RepeaterPage), true)
#42 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterPage), Object(ProcessWire\RepeaterPage), true)
#43 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\FieldsetPage), Object(ProcessWire\FieldsetPage), true)
#44 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\Page), Object(ProcessWire\Page), true)
#45 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterMatrixPage), Object(ProcessWire\RepeaterMatrixPage), true)
#46 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\Page), Object(ProcessWire\Page), true)
#47 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\FieldsetPage), Object(ProcessWire\FieldsetPage), true)
#48 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterPage), Object(ProcessWire\RepeaterPage), true)
#49 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterPage), Object(ProcessWire\RepeaterPage), true)
#50 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\FieldsetPage), Object(ProcessWire\FieldsetPage), true)
#51 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\Page), Object(ProcessWire\Page), true)
#52 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterMatrixPage), Object(ProcessWire\RepeaterMatrixPage), true)
#53 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\Page), Object(ProcessWire\Page), true)
#54 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\FieldsetPage), Object(ProcessWire\FieldsetPage), true)
#55 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterPage), Object(ProcessWire\RepeaterPage), true)
#56 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterPage), Object(ProcessWire\RepeaterPage), true)
#57 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\FieldsetPage), Object(ProcessWire\FieldsetPage), true)
#58 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\Page), Object(ProcessWire\Page), true)
#59 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterMatrixPage), Object(ProcessWire\RepeaterMatrixPage), true)
#60 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\Page), Object(ProcessWire\Page), true)
#61 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\FieldsetPage), Object(ProcessWire\FieldsetPage), true)
#62 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterPage), Object(ProcessWire\RepeaterPage), true)
#63 htdocs\site\modules\ProDrafts\ProDrafts.module(1037): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterPage), Object(ProcessWire\RepeaterPage), true)
#64 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\FieldsetPage), Object(ProcessWire\FieldsetPage), true)
#65 htdocs\site\modules\ProDrafts\ProDrafts.module(1026): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\Page), Object(ProcessWire\Page), true)
#66 htdocs\site\modules\ProDrafts\ProDraft.php(827): ProcessWire\ProDrafts->getPageDifferences(Object(ProcessWire\RepeaterPage), Object(ProcessWire\RepeaterPage), true)
#67 htdocs\site\modules\ProDrafts\ProDrafts.module(1226): ProcessWire\ProDraft->hasChanges(3)
#68 htdocs\site\modules\ProDrafts\ProDrafts.module(912): ProcessWire\ProDrafts->saveDraft(Object(ProcessWire\ProDraft))
#69 htdocs\wire\core\Wire.php(397): ProcessWire\ProDrafts->___approveRequestPublish(Object(ProcessWire\ProDraft))
#70 htdocs\wire\core\WireHooks.php(823): ProcessWire\Wire->_callMethod('___approveReque...', Array)
#71 htdocs\wire\core\Wire.php(465): ProcessWire\WireHooks->runHooks(Object(ProcessWire\ProDrafts), 'approveRequestP...', Array)
#72 htdocs\site\modules\ProDrafts\ProDraftsPageEditorHooks.php(506): ProcessWire\Wire->__call('approveRequestP...', Array)
#73 htdocs\wire\core\WireHooks.php(924): ProcessWire\ProDraftsPageEditorHooks->hookEditLoadPage(Object(ProcessWire\HookEvent))
#74 htdocs\wire\core\Wire.php(465): ProcessWire\WireHooks->runHooks(Object(ProcessWire\ProcessPageEdit), 'loadPage', Array)
#75 htdocs\wire\modules\Process\ProcessPageEdit\ProcessPageEdit.module(396): ProcessWire\Wire->__call('loadPage', Array)
#76 htdocs\wire\core\Modules.php(629): ProcessWire\ProcessPageEdit->init()
#77 htdocs\wire\core\Modules.php(1341): ProcessWire\Modules->initModule(Object(ProcessWire\ProcessPageEdit), Array)
#78 htdocs\wire\core\ProcessController.php(165): ProcessWire\Modules->getModule('ProcessPageEdit', Array)
#79 htdocs\wire\core\ProcessController.php(321): ProcessWire\ProcessController->getProcess()
#80 htdocs\wire\core\Wire.php(394): ProcessWire\ProcessController->___execute()
#81 htdocs\wire\core\WireHooks.php(823): ProcessWire\Wire->_callMethod('___execute', Array)
#82 htdocs\wire\core\Wire.php(465): ProcessWire\WireHooks->runHooks(Object(ProcessWire\ProcessController), 'execute', Array)
#83 htdocs\wire\core\admin.php(153): ProcessWire\Wire->__call('execute', Array)
#84 htdocs\wire\modules\AdminTheme\AdminThemeUikit\controller.php(15): require('pw\\htdocs\\...')
#85 htdocs\site\templates\admin.php(28): require('pw\\htdocs\\...')
#86 htdocs\wire\core\TemplateFile.php(318): require('pw\\htdocs\\...')
#87 htdocs\wire\core\Wire.php(394): ProcessWire\TemplateFile->___render()
#88 htdocs\wire\core\WireHooks.php(823): ProcessWire\Wire->_callMethod('___render', Array)
#89 htdocs\wire\core\Wire.php(465): ProcessWire\WireHooks->runHooks(Object(ProcessWire\TemplateFile), 'render', Array)
#90 htdocs\wire\modules\PageRender.module(536): ProcessWire\Wire->__call('render', Array)
#91 htdocs\wire\core\Wire.php(397): ProcessWire\PageRender->___renderPage(Object(ProcessWire\HookEvent))
#92 htdocs\wire\core\WireHooks.php(823): ProcessWire\Wire->_callMethod('___renderPage', Array)
#93 htdocs\wire\core\Wire.php(465): ProcessWire\WireHooks->runHooks(Object(ProcessWire\PageRender), 'renderPage', Array)
#94 htdocs\wire\core\WireHooks.php(924): ProcessWire\Wire->__call('renderPage', Array)
#95 htdocs\wire\core\Wire.php(465): ProcessWire\WireHooks->runHooks(Object(ProcessWire\Page), 'render', Array)
#96 htdocs\wire\modules\Process\ProcessPageView.module(213): ProcessWire\Wire->__call('render', Array)
#97 htdocs\wire\core\Wire.php(397): ProcessWire\ProcessPageView->___execute(true)
#98 htdocs\wire\core\WireHooks.php(823): ProcessWire\Wire->_callMethod('___execute', Array)
#99 htdocs\wire\core\Wire.php(465): ProcessWire\WireHooks->runHooks(Object(ProcessWire\ProcessPageView), 'execute', Array)
#100 htdocs\index.php(55): ProcessWire\Wire->__call('execute', Array)
#101 {main}
```

**Comment by apeisa** [comment]
This might be related to this issue https://github.com/processwire/processwire-issues/issues/572 that is now fixed in dev branch. Can you try if your issue still exists of you update to dev branch?

**Comment by Radon8472** [comment]
> 
> This might be related to this issue #572 that is now fixed in dev branch. Can you try if your issue still exists of you update to dev branch?

@apeisa #572 seems to be a very similar problem, but I can`t see any changes that would effect the ProDrafts Modul.
Can you tell me where I can find the dev branch of ProDrafts with this changes ?

**Comment by Radon8472** [comment]
@apeisa 
I think the changes for #572 are yust that in commit processwire/processwire@8dbff5c7bc367e805badf51204b4e31123cf9b6e .
If that is all that has been changed for this issue, I am sure that it won`t have any impacts on the problem with ProDrafts.

I could show where in the ProDrafts modul is the place in the code that must be change, but I am not sure if is is a good idea to post code of a paid module in a public thread.

**Comment by ryancramerdesign** [comment]
@Radon8472 Thanks for the report. This method does need to compare differences in Page and PageArray objects, so that it can compute differences in FieldtypeFieldsetPage and FieldtypeRepeater fields. But I think you are right that it could reduce the check for Page reference fields to something simpler, since it doesn't need to traverse into them. The thing is, my line numbers are very different from yours, so want to make sure I understand what you are proposing correctly. In the getPageDifferences() method, there's a foreach() with an if() statement in there that checks what kind of value it's dealing with and whether it should go recursive, etc. Theoretically, adding a new second condition to that if() statement that checks for the Page field (as you mentioned) and reduces it to a string comparison, should prevent it from going recursive for this case. Can you confirm? Here's what I'm adding:
~~~~
} else if($isObject && $field->type instanceof FieldtypePage) {
  $different = "$value1" !== "$value2";
} else if(...existing code...
~~~~
Thanks, and please let me know what you find. I'm closing this report since we aren't supposed to use this repo for non-core stuff, but we can keep the conversation going even though it's closed, or we can move it to the ProDrafts board.

**Comment by Radon8472** [comment]
@ryancramerdesign the line numbers I posted match to `'version' => 8, ` (The modul config shows 0.0.8).
You are right in getPageDifferences I found 2 places where the function calls itself recursively, one after the 

```php
if($isObject && ($value1 instanceof Page && $value2 instanceof Page)) {
```
and one after
```php
if($isObject && ($value1 instanceof PageArray && $value2 instanceof PageArray)) {
```
a few lines later within the while loop that walks over all Elements in PageArray.

Both of this calls need a check, that the comparison for Page field is reduced e.g. to comparision of the target pages ID to skip the recursive call for this field.

p.s. I posted this here, because I already found another ProDrafts issue here. When this is the wrong place let me know where I should post issues for ProDrafts.

**Comment by ryancramerdesign** [comment]
@Radon8472 The check I'm thinking of would come before either of those lines you mentioned. Here's a more complete example:
~~~~~
foreach($page1->template->fieldgroup as $field) {
			
	$value1 = $page1->get($field->name);
	$value2 = $page2->get($field->name);
	$different = false;
	$isObject = is_object($value1) && is_object($value2);
	
	if((empty($value1) && !empty($value2)) || (!empty($value1) && empty($value2))) {
		$different = true;

	// ADDED THESE 2 LINES BELOW:
	} else if($isObject && $field->type instanceof FieldtypePage) {
		$different = "$value1" !== "$value2"; 

	} else if($isObject && ($value1 instanceof Page && $value2 instanceof Page)) {
		$different = count($this->getPageDifferences($value1, $value2, true)) > 0;
			
	} else if($isObject && ($value1 instanceof PageArray && $value2 instanceof PageArray)) {
...
~~~~~

**Comment by Radon8472** [comment]
> 
> 
> @Radon8472 The check I'm thinking of would come before either of those lines you mentioned. Here's a more complete example:
> 
> ```
> foreach($page1->template->fieldgroup as $field) {
> 			
> 	$value1 = $page1->get($field->name);
> 	$value2 = $page2->get($field->name);
> 	$different = false;
> 	$isObject = is_object($value1) && is_object($value2);
> 	
> 	if((empty($value1) && !empty($value2)) || (!empty($value1) && empty($value2))) {
> 		$different = true;
> 
> 	// ADDED THESE 2 LINES BELOW:
> 	} else if($isObject && $field->type instanceof FieldtypePage) {
> 		$different = "$value1" !== "$value2"; 
> 
> 	} else if($isObject && ($value1 instanceof Page && $value2 instanceof Page)) {
> 		$different = count($this->getPageDifferences($value1, $value2, true)) > 0;
> 			
> 	} else if($isObject && ($value1 instanceof PageArray && $value2 instanceof PageArray)) {
> ...
> ```

Yes that sounds perfect, i think that should solve the issue.
