### ISSUE TITLE
Profields Table: accessing empty text field throws an error (report cancelled, error is caused by Twig module)

### ISSUE THREAD

**Issue by hiboudev** [processwire/processwire-issues#1827]
**EDIT** **I didn't look at stack trace... This error is caused by Twig extension, so I close the report.**

### Short description of the issue

Accessing an empty Text field inside a Profields Table throws this error:

> Look out… Erreur fatale: Uncaught Error: An exception has been thrown during the rendering of a template ("Method TableRow::reason does not exist or is not callable in this context").
> #0 src-processwire\vendor\twig\twig\src\Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
> #1 src-processwire\vendor\twig\twig\src\Template.php(379): Twig\Template->display(Array)
> #2 src-processwire\vendor\twig\twig\src\TemplateWrapper.php(40): Twig\Template->render(Array, Array)
> #3 src-processwire\vendor\twig\twig\src\Extension\CoreExtension.php(1347): Twig\TemplateWrapper->render(Array)
> #4 src-processwire\site\assets\cache\TemplateEngineTwig_compile\8a\8a22dcf5304fc7aba24e035ffbf589d2.php(61): twig_include(Object(Twig\Environment), Array, 'fragments/race/...', Array)

If the field has a value, no error is thrown.

### Expected behavior

Getting an empty string.

### Actual behavior

Getting an error.

### Steps to reproduce the issue

1. Create a Profields Table field with several fields including one Text field,
2. In the page using this Table, add a row and keep the Text field empty.
3. In PHP, loop over the Table rows, accessing the Text field value.

### Setup/Environment

* ProcessWire version: 3.0.228
* (Optional) PHP version: 8.1

**Comment by hiboudev** [comment]
Error happens only from Twig.
