### ISSUE TITLE
Admin error when switching to UIKit Admin theme

### ISSUE THREAD

**Issue by kalmarlansmuseum** [processwire/processwire-issues#452]
Short description of the issue
After updating to latest dev and changing to UIkit admin theme i get the following error:

```

Error: Uncaught Error: Call to a member function addBodyClass() on null in /wire/modules/LanguageSupport/LanguageTabs.module:114
Stack trace:
#0 /wire/core/WireHooks.php(808): ProcessWire\LanguageTabs->hookRenderInputfieldForm(Object(ProcessWire\HookEvent))
#1 /wire/core/Wire.php(442): ProcessWire\WireHooks->runHooks(Object(ProcessWire\InputfieldForm), 'render', Array)
#2 /wire/modules/Process/ProcessProfile/ProcessProfile.module(86): ProcessWire\Wire->__call('render', Array)
#3 /wire/core/Wire.php(380): ProcessWire\ProcessProfile->___execute()
#4 /wire/core/WireHooks.php(714): ProcessWire\Wire->_callMethod('___execute', Array)
#5 /wire/core/Wire.php(442): ProcessWire\WireHooks-> (line 114 of /wire/modules/LanguageSupport/LanguageTabs.module) 

This error message was shown because: you are logged in as a Superuser. Error has been logged.
```

Expected behavior
No error

Actual behavior
Admin error

Optional: Suggestion for a possible fix
Disabling LanguageTabs.module gets the admin back on track but with the basic/old theme.

Steps to reproduce the issue
Update to latest dev
Change to UI kit admin

Setup/Environment
ProcessWire version: latest dev

**Comment by elabx** [comment]
Can confirm I got this error updating from 3.0.77 to latest dev.

**Comment by ryancramerdesign** [comment]
I can't seem to duplicate it here, but maybe it's got something to do with a combination of modules or other conditions that need to be present. The error message is easy for me to fix (which I just pushed), but curious to know if that resolves it, or just reveals another error? Thanks.

**Comment by netcarver** [comment]
@kalmarlansmuseum Hello. Can you verify if this issue still exists or is resolved now? If resolved, please could you close this issue. If it still exists, please add to the conversation here. Thank you.

**Comment by netcarver** [comment]
Closing due to inactivity.
