### ISSUE TITLE
Error occurs if "advanced mode" is true and trying to create a field using the "Cache" fieldtype

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#535]
If advanced mode is on (in config.php):
```
$config->advanced = true;
```

... and you've installed the "Cache" module (FieldtypeCache), and you create a field with that module, I get the following error:
```
Error: Uncaught Error: Call to a member function getConfigAllowContext() on null in /mywebsite/wire/modules/Process/ProcessField/ProcessField.module:1015
Stack trace:
#0 /mywebsite/wire/core/Wire.php(383): ProcessWire\ProcessField->___buildEditFormContext(Object(ProcessWire\InputfieldForm))
#1 /mywebsite/wire/core/WireHooks.php(723): ProcessWire\Wire->_callMethod('___buildEditFor...', Array)
#2 /mywebsite/wire/core/Wire.php(442): ProcessWire\WireHooks->runHooks(Object(ProcessWire\ProcessField), 'buildEditFormCo...', Array)
#3 /mywebsite/wire/modules/Process/ProcessField/ProcessField.module(830): ProcessWire\Wire->__call('buildEditFormCo...', Array)
#4 /mywebsite/wire/core/Wire.php(380): ProcessWire\ProcessField->___buildEditForm()
#5 /mywebsite/wire/core/WireHooks.php(723): ProcessWire\Wir (line 1015 of /mywebsite/wire/modules/Process/ProcessField/ProcessField.module) 

This error message was shown because: you are logged in as a Superuser. Error has been logged. Administrator has been notified.
```

If turning off advanced mode, the error does not occur.

**Comment by matjazpotocnik** [comment]
I can confirm this behavior. `$this->field->getInputfield($dummyPage`) on line 1015 returns NULL. The check for advanced mode is at line 915. I'm not sure what would be the correct fix, but I guess a check for null wouldn't hurt?

**Comment by ryancramerdesign** [comment]
Thanks, I've pushed a fix for this issue.
