### ISSUE TITLE
Matrix: ProcessPageEdit: Method RepeaterMatrixPage::summarize does not exist or is not callable in this context

### ISSUE THREAD

**Issue by jlahijani** [processwire/processwire-issues#937]
I'm getting the error shown below when editing a page that has a matrix field.  I'm not sure why this is happening.  I'm using the latest version of Matrix and PW.  I have a nearly identical setup on 4 other sites without an issue.  I tried clearing module compiled files.  The pages load fine on the frontend however.

Disabling the line that creates the summary in InputfieldRepeaterMatrix.module (line 107) alleviates the issue, but of course I won't have a summary.

Note to self: occurring on "Wilco" site.

```
ProcessWire: ProcessPageEdit: Method RepeaterMatrixPage::summarize does not exist or is not callable in this context

#0 /wire/core/Page.php(1873): ProcessWire\Wire->___callUnknown('summarize', Array)
#1 /wire/core/Wire.php(386): ProcessWire\Page->___callUnknown('summarize', Array)
#2 /wire/core/WireHooks.php(733): ProcessWire\Wire->_callMethod('___callUnknown', Array)
#3 /wire/core/Wire.php(442): ProcessWire\WireHooks->runHooks(Object(ProcessWire\RepeaterMatrixPage), 'callUnknown', Array)
#4 /wire/core/Wire.php(445): ProcessWire\Wire->__call('callUnknown', Array)
#5 /site/modules/FieldtypeRepeaterMatrix/InputfieldRepeaterMatrix.module(107): ProcessWire\Wire->__call('summarize', Array)
#6 /wire/core/Wire.php(389): ProcessWire\InputfieldRepeaterMatrix->___renderRepeaterLabel('Section', 1, Object(ProcessWire\RepeaterMatrixPage))
#7 /wire/core/WireHooks.php(733): ProcessWire\Wire->_callMethod('___renderRepeat...', Array)
#8 /wire/core/Wire.php(442): ProcessWire\WireHooks->runHooks(Object(ProcessWire\InputfieldRepeaterMatrix), 'renderRepeaterL...', Array)
#9 /wire/modules/Fieldtype/FieldtypeRepeater/InputfieldRepeater.module(396): ProcessWire\Wire->__call('renderRepeaterL...', Array)
#10 /wire/modules/Fieldtype/FieldtypeRepeater/InputfieldRepeater.module(735): ProcessWire\InputfieldRepeater->buildForm(0, Array)
#11 /site/modules/FieldtypeRepeaterMatrix/InputfieldRepeaterMatrix.module(350): ProcessWire\InputfieldRepeater->___render()
#12 /wire/core/Wire.php(380): ProcessWire\InputfieldRepeaterMatrix->___render()
#13 /wire/core/WireHooks.php(733): ProcessWire\Wire->_callMethod('___render', Array)
#14 /wire/core/Wire.php(442): ProcessWire\WireHooks->runHooks(Object(ProcessWire\InputfieldRepeaterMatrix), 'render', Array)
#15 /wire/core/InputfieldWrapper.php(801): ProcessWire\Wire->__call('render', Array)
#16 /wire/core/Wire.php(386): ProcessWire\InputfieldWrapper->___renderInputfield(Object(ProcessWire\InputfieldRepeaterMatrix), false)
#17 /wire/core/WireHooks.php(733): ProcessWire\Wire->_callMethod('___renderInputf...', Array)
#18 /wire/core/Wire.php(442): ProcessWire\WireHooks->runHooks(Object(ProcessWire\InputfieldWrapper), 'renderInputfiel...', Array)
#19 /wire/core/InputfieldWrapper.php(486): ProcessWire\Wire->__call('renderInputfiel...', Array)
#20 /wire/core/Wire.php(380): ProcessWire\InputfieldWrapper->___render()
#21 /wire/core/WireHooks.php(733): ProcessWire\Wire->_callMethod('___render', Array)
#22 /wire/core/Wire.php(442): ProcessWire\WireHooks->runHooks(Object(ProcessWire\InputfieldWrapper), 'render', Array)
#23 /wire/core/InputfieldWrapper.php(801): ProcessWire\Wire->__call('render', Array)
#24 /wire/core/Wire.php(386): ProcessWire\InputfieldWrapper->___renderInputfield(Object(ProcessWire\InputfieldWrapper), false)
#25 /wire/core/WireHooks.php(733): ProcessWire\Wire->_callMethod('___renderInputf...', Array)
#26 /wire/core/Wire.php(442): ProcessWire\WireHooks->runHooks(Object(ProcessWire\InputfieldForm), 'renderInputfiel...', Array)
#27 /wire/core/InputfieldWrapper.php(486): ProcessWire\Wire->__call('renderInputfiel...', Array)
#28 /wire/modules/Inputfield/InputfieldForm.module(143): ProcessWire\InputfieldWrapper->___render()
#29 /wire/core/Wire.php(380): ProcessWire\InputfieldForm->___render()
#30 /wire/core/WireHooks.php(733): ProcessWire\Wire->_callMethod('___render', Array)
#31 /wire/core/Wire.php(442): ProcessWire\WireHooks->runHooks(Object(ProcessWire\InputfieldForm), 'render', Array)
#32 /wire/modules/Process/ProcessPageEdit/ProcessPageEdit.module(603): ProcessWire\Wire->__call('render', Array)
#33 /wire/modules/Process/ProcessPageEdit/ProcessPageEdit.module(569): ProcessWire\ProcessPageEdit->renderEdit()
#34 /wire/core/Wire.php(380): ProcessWire\ProcessPageEdit->___execute()
#35 /wire/core/WireHooks.php(733): ProcessWire\Wire->_callMethod('___execute', Array)
#36 /wire/core/Wire.php(442): ProcessWire\WireHooks->runHooks(Object(ProcessWire\ProcessPageEdit), 'execute', Array)
#37 /wire/core/ProcessController.php(337): ProcessWire\Wire->__call('execute', Array)
#38 /wire/core/Wire.php(380): ProcessWire\ProcessController->___execute()
#39 /wire/core/WireHooks.php(733): ProcessWire\Wire->_callMethod('___execute', Array)
#40 /wire/core/Wire.php(442): ProcessWire\WireHooks->runHooks(Object(ProcessWire\ProcessController), 'execute', Array)
#41 /wire/core/admin.php(150): ProcessWire\Wire->__call('execute', Array)
#42 /wire/modules/AdminTheme/AdminThemeUikit/controller.php(15): require('/mnt/c/Users/jl...')
#43 /site/templates/admin.php(31): require('/mnt/c/Users/jl...')
#44 /wire/core/TemplateFile.php(287): require('/mnt/c/Users/jl...')
#45 /wire/core/Wire.php(380): ProcessWire\TemplateFile->___render()
#46 /wire/core/WireHooks.php(733): ProcessWire\Wire->_callMethod('___render', Array)
#47 /wire/core/Wire.php(442): ProcessWire\WireHooks->runHooks(Object(ProcessWire\TemplateFile), 'render', Array)
#48 /wire/modules/PageRender.module(514): ProcessWire\Wire->__call('render', Array)
#49 /wire/core/Wire.php(383): ProcessWire\PageRender->___renderPage(Object(ProcessWire\HookEvent))
#50 /wire/core/WireHooks.php(733): ProcessWire\Wire->_callMethod('___renderPage', Array)
#51 /wire/core/Wire.php(442): ProcessWire\WireHooks->runHooks(Object(ProcessWire\PageRender), 'renderPage', Array)
#52 /wire/core/WireHooks.php(834): ProcessWire\Wire->__call('renderPage', Array)
#53 /wire/core/Wire.php(442): ProcessWire\WireHooks->runHooks(Object(ProcessWire\Page), 'render', Array)
#54 /wire/modules/Process/ProcessPageView.module(209): ProcessWire\Wire->__call('render', Array)
#55 /wire/core/Wire.php(383): ProcessWire\ProcessPageView->___execute(true)
#56 /wire/core/WireHooks.php(733): ProcessWire\Wire->_callMethod('___execute', Array)
#57 /wire/core/Wire.php(442): ProcessWire\WireHooks->runHooks(Object(ProcessWire\ProcessPageView), 'execute', Array)
#58 /index.php(55): ProcessWire\Wire->__call('execute', Array)
#59 {main}
```

**Comment by jlahijani** [comment]
Turns out this is not a bug, but rather my local web server, which is WSL-based, is really buggy.  Restarting my server resolved the issue.  Nothing to see here!
